spring:
  application:
    name: api-gateway
zuul:
  routes:
#    sensitiveHeaders: #允许cookie传递到后端
    myProduct: #自定义路由
      path: /myProduct/**
      serviceId: product
      sensitiveHeaders: #允许cookie传递到后端
#    product: /myProduct/** #自定义路由 - 简洁写法
  ignored-patterns: #排除某些路由请求
    - /**/product/listForOrder
